//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactRecords
    {
        public int PersonId { get; set; }
        public string PersonName { get; set; }
        public string CompanyName { get; set; }
        public byte[] ProfileImage { get; set; }
        public string Email { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string PhoneNumberHome { get; set; }
        public string PhoneNumberWork { get; set; }
        public string Addressnumber { get; set; }
    }
}
